[FLINK-20352][dos] Add PyFlink job submission section under the Advanced CLI section.
XComp/flink pull request #1
Opened 2020-12-09 09:57 UTC by shuiqiangchen

## What is the purpose of the change

*Add PyFlink job submission section under the Advanced CLI section.*

![image](https://user-images.githubusercontent.com/44767915/101614403-dbd21780-3a47-11eb-8762-84f1ac12ffe7.png)

2020-12-10 10:22 UTC, XComp requested changes
Thank you @shuiqiangchen for the changes. I added some remarks, mostly formatting issues.

But there are two cases where the command seem to be wrong. It would be great if you could check those.

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +Currently users are able to submit a PyFlink job via the CLI. It does not require to specify the
```suggestion
Currently, users are able to submit a PyFlink job via the CLI. It does not require to specify the
```

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +jar file path or the entry main class, which is different from the Java job submission. The followings
```suggestion
JAR file path or the entry main class, which is different from the Java job submission. The followings
```
Just to be consistent with the other formattings (I realized that there its formatted wrongly twice in the CLI actions as well. I'm gonna fix that).

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +are some example of PyFlink job submission:
I would move the last sentence after the Python version check and rename it slightly: `The following commands show different PyFlink job submission use-cases:`

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +<span class="label label-info">Note</span> When submitting Python job via `flink run`, Flink will run the command “python”. Please run the following command to confirm that the command “python” in cu
```suggestion
<span class="label label-info">Note</span> When submitting Python job via `flink run`, Flink will run the command "python". Please run the following command to confirm that the `PATH` variable is pointing to a supported Python version: 3.5, 3.6, 3.7 or 3.8
```

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +<span class="label label-info">Note</span> When submitting Python job via `flink run`, Flink will run the command “python”. Please run the following command to confirm that the command “python” in cu
Is it save to say that we support `3.5+`? If yes, I would prefer that notation over listing each Python version as this might change over time.

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +# the version printed here must be 3.5, 3.6, 3.7 or 3.8
Here as well: We could switch to `3.5+` if possible

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +$ ./bin/flink run -py examples/python/table/batch/word_count.py
```suggestion
$ ./bin/flink run --python examples/python/table/batch/word_count.py
```
We decided to stick to long parameters in the documentation for the sake of readability.

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +      -pyfs file:///user.txt,hdfs:///$namenode_address/username.txt
```suggestion
$ ./bin/flink run \
      --python examples/python/table/batch/word_count.py \
      --pyFiles file:///user.txt,hdfs:///$namenode_address/username.txt
```
Long parameters, aligned indentation and parameter listing.

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +$ ./bin/flink run -py examples/python/table/batch/word_count.py -j <jarFile>
```suggestion
$ ./bin/flink run \
      --python examples/python/table/batch/word_count.py \
      --jarfile <jarFile>
```
Long parameters, aligned indentation and parameter listing.

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +$ ./bin/flink run -py examples/python/table/batch/word_count.py -j <jarFile>
```suggestion
$ ./bin/flink run -py examples/python/table/batch/word_count.py -pyfs file:///user.txt,hdfs:///$namenode_address/username.txt -pym word_count
```
It does not match the description. Is the above statement the correct one?

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +$ ./bin/flink run -py examples/python/table/batch/word_count.py -j <jarFile>
Additionally, here's a reformatted version:
```
$ ./bin/flink run \
      --python examples/python/table/batch/word_count.py \
      --pyFiles file:///user.txt,hdfs:///$namenode_address/username.txt \
      --pyModule word_count
```

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +$ ./bin/flink run -m myJMHost:8081 -py examples/python/table/batch/word_count.py
```suggestion
- Submit a Python Table job on a specific JobManager running a on host `<jobmanagerHost>` (adapt the 
command accordingly):
{% highlight bash %}
$ ./bin/flink run \
      --jobmanager <jobmanagerHost>:8081 \
      --python examples/python/table/batch/word_count.py
```

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +- Run a Python Table job using a [per-job YARN cluster]({% link deployment/resource-providers/yarn.md %}#run-a-single-flink-job-on-hadoop-yarn) with 2 TaskManagers:
```suggestion
- Run a Python Table job using a [YARN cluster in Per-Job Mode]({% link deployment/resource-providers/yarn.md %}#run-a-single-flink-job-on-hadoop-yarn) with 2 TaskManagers:
```
Just aligning the text with some naming rules we agreed on during the docs refactoring.

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +$ ./bin/flink run -m yarn-cluster -py examples/python/table/batch/word_count.py
```suggestion
$ ./bin/flink run -m yarn-cluster -py examples/python/table/batch/word_count.py
```
Where are the two TaskManagers specified? 🤔

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +$ ./bin/flink run -m yarn-cluster -py examples/python/table/batch/word_count.py
```suggestion
$ ./bin/flink run --target yarn-per-job -py examples/python/table/batch/word_count.py
```
Isn't `-m` wrong here as it refers to the JobManager?

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +$ ./bin/flink run -m yarn-cluster -py examples/python/table/batch/word_count.py
Additionally, we want the format of the command to be aligned with the other commands, i.e. long parameters, 6 space indentation and one parameter per line:
```
./bin/flink run \
      --target yarn-per-job \
      --python examples/python/table/batch/word_count.py
```
You might adapt the parameters to fit to the description accordingly.

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +- Run a Python Table application on a native Kubernetes cluster:
```suggestion
- Run a Python Table application on a native Kubernetes cluster having the cluster ID `<ClusterId>`:
```

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +  -pym word_count -pyfs /opt/flink/examples/python/table/batch/word_count.py
```suggestion
$ ./bin/flink run-application \
      --parallelism 8 \
      --target kubernetes-application \
      -Dkubernetes.cluster-id=<ClusterId> \
      -Dtaskmanager.memory.process.size=4096m \
      -Dkubernetes.taskmanager.cpu=2 \
      -Dtaskmanager.numberOfTaskSlots=4 \
      -Dkubernetes.container.image=<PyFlinkImageName> \
      --pyModule word_count \
      --pyFiles /opt/flink/examples/python/table/batch/word_count.py
```

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.md
> +  -pym word_count -pyfs /opt/flink/examples/python/table/batch/word_count.py
I would also suggest moving the `--target` parameter up in the listing as it's directly connected to `run-application`.

2020-12-10 10:22 UTC, XComp commented on docs/deployment/cli.zh.md
> +### Submitting PyFlink Jobs
It appears (after having only a brief look over it) that the comments I gave on the English version apply on the Chinese version as well.

2020-12-11 01:56 UTC, shuiqiangchen commented on docs/deployment/cli.md
> +<span class="label label-info">Note</span> When submitting Python job via `flink run`, Flink will run the command “python”. Please run the following command to confirm that the command “python” in cu
After double checking, Python 3.5 is no longer supported in release-1.11+, so we can remove 3.5 here.

2020-12-11 02:19 UTC, shuiqiangchen commented on docs/deployment/cli.md
> +$ ./bin/flink run -m yarn-cluster -py examples/python/table/batch/word_count.py
Sorry, my mistake, running jobs on Yarn in Per-Job Mode will allocate and de-allocate taskmanagers dynamically, so there is no need to specify the number of taskmanagers.

2020-12-11 02:46 UTC, shuiqiangchen commented on docs/deployment/cli.md
> +<span class="label label-info">Note</span> When submitting Python job via `flink run`, Flink will run the command “python”. Please run the following command to confirm that the command “python” in cu
The path of the python executable might not be configured in `PATH` variable.

2020-12-11 02:59 UTC, shuiqiangchen commented
@XComp Highly appreciate for your comments, I have updated the PR according to your suggestions. And I will create a new Apache Flink PR as you suggested. So this PR could be closed.

2020-12-24 09:50 UTC, closed without merging